# Header
menu:
  Home: /
  Archives: /archives
rss:

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tagcloud
# - archive
- recent_posts
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- tagcloud
- archive
# - category

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /css/images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: